/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugHistoryRouteImport } from './routes/$slug/history'
import { Route as SlugEditRouteImport } from './routes/$slug/edit'
import { Route as SlugHistoryIdRouteImport } from './routes/$slug/history/$id'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugHistoryRoute = SlugHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => SlugRoute,
} as any)
const SlugEditRoute = SlugEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => SlugRoute,
} as any)
const SlugHistoryIdRoute = SlugHistoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SlugHistoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/$slug/edit': typeof SlugEditRoute
  '/$slug/history': typeof SlugHistoryRouteWithChildren
  '/$slug/history/$id': typeof SlugHistoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/$slug/edit': typeof SlugEditRoute
  '/$slug/history': typeof SlugHistoryRouteWithChildren
  '/$slug/history/$id': typeof SlugHistoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/$slug/edit': typeof SlugEditRoute
  '/$slug/history': typeof SlugHistoryRouteWithChildren
  '/$slug/history/$id': typeof SlugHistoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/login'
    | '/logout'
    | '/$slug/edit'
    | '/$slug/history'
    | '/$slug/history/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/login'
    | '/logout'
    | '/$slug/edit'
    | '/$slug/history'
    | '/$slug/history/$id'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/login'
    | '/logout'
    | '/$slug/edit'
    | '/$slug/history'
    | '/$slug/history/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/history': {
      id: '/$slug/history'
      path: '/history'
      fullPath: '/$slug/history'
      preLoaderRoute: typeof SlugHistoryRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/edit': {
      id: '/$slug/edit'
      path: '/edit'
      fullPath: '/$slug/edit'
      preLoaderRoute: typeof SlugEditRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/history/$id': {
      id: '/$slug/history/$id'
      path: '/$id'
      fullPath: '/$slug/history/$id'
      preLoaderRoute: typeof SlugHistoryIdRouteImport
      parentRoute: typeof SlugHistoryRoute
    }
  }
}

interface SlugHistoryRouteChildren {
  SlugHistoryIdRoute: typeof SlugHistoryIdRoute
}

const SlugHistoryRouteChildren: SlugHistoryRouteChildren = {
  SlugHistoryIdRoute: SlugHistoryIdRoute,
}

const SlugHistoryRouteWithChildren = SlugHistoryRoute._addFileChildren(
  SlugHistoryRouteChildren,
)

interface SlugRouteChildren {
  SlugEditRoute: typeof SlugEditRoute
  SlugHistoryRoute: typeof SlugHistoryRouteWithChildren
}

const SlugRouteChildren: SlugRouteChildren = {
  SlugEditRoute: SlugEditRoute,
  SlugHistoryRoute: SlugHistoryRouteWithChildren,
}

const SlugRouteWithChildren = SlugRoute._addFileChildren(SlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
